### ISSUE TITLE
Failed to seek file to position: 0

### ISSUE THREAD

**Issue by YuqiHUO** [dmlc/decord#100]
Hi, I recently find that the pypi 0.4.1 version has little bug while 0.4.0 doesn't have. Building from the latest resource result in the same issues.

import VideoReader, cpu
vr = VideoReader(video_path)
and will return error
 /io/decord/src/video/video_reader.cc:280:  Failed to seek file to position: 0
can you fix it? or I can only use the 0.4.0 version

**Comment by zhreshold** [comment]
It's a warning indicating a failed seek, do you still get reasonable frames?

**Comment by YuqiHUO** [comment]
no, after the warning, I can get the correct length by len(vr), but can't get any frames. When I try vr[0], the program will exit by failed-seeking error.

**Comment by YuqiHUO** [comment]
I locate the error, the seeking is fine at #75 but has error at #77 .
The only change between this two commitment is at src/video/video_reader.cc  FrameToPTS
[See here](https://github.com/dmlc/decord/commit/449a9ffe8aaace5606007d9b98a2cdc15d89d9ac)
In pos=0, the previous code calculated the correct ts = 0 while the code now calculate the wrong ts = -9********

**Comment by YuqiHUO** [comment]
My test code is:
`int64_t VideoReader::FrameToPTS(int64_t pos) {
    LOG(WARNING) << "Position is now: " << pos;
    int64_t ts = frame_ts_[pos].pts;
    // int64_t ts = pos * fmt_ctx_->streams[actv_stm_idx_]->duration / GetFrameCount();
    LOG(WARNING) << "TS is now: " << ts;
    return ts;
}`
@zhreshold  @JoannaLXY  can you help to check the commit? thx

**Comment by YuqiHUO** [comment]
#88 The same problem

**Comment by YuqiHUO** [comment]
I test two videos in examples, it's ok, but the error happens to some old-format videos (In this case, videos in HMDB51/UCF101)

**Comment by YuqiHUO** [comment]
I modified the code to solve it while keeping the new feature:
![image](https://user-images.githubusercontent.com/28945001/96071047-f36fa280-0ed3-11eb-93ed-40c91cc5574a.png)
ts=-9223372036854775808 maybe an undefined pts in old-format videos.
My solution is just temporary, @zhreshold @JoannaLXY can you guys fix it?

**Comment by zhreshold** [comment]
Maybe it's more robust for frame based seeking, I can try it first

**Comment by zhreshold** [comment]
@YuqiHUO See #103, please verify with the legacy video, I may not be able to reproduce due to the different in video formats.

**Comment by YuqiHUO** [comment]
The version now works, thanks.

**Comment by ooguz166** [comment]
Apparently, if you update 0.5.0 version to 0.6.0 problem fades away but sometimes it may cause messed up vr-envs. In such case, create a new one, before torch or mxnet installations install 0.6.0
