### ISSUE TITLE
Cannot get the same result with cv2.VideoCapture

### ISSUE THREAD

**Issue by Hao-Tju** [dmlc/decord#108]
The frames obtained with cv2.VideoCapture is different with that with decord.VideoReader.

Code to reproduce this issue:
```python
import cv2
import decord as de

video = 'test.mp4'
cv2_reader = cv2.VideoCapture(video)
dmlc_reader = de.VideoReader(video)

ret, cv2_img = cv2_reader.read()
dmlc_img = dmlc_reader[0].asnumpy()   # add asnumpy.

print((cv2_img == dmlc_img).all())    # False

# To check whether it is because OpenCV's default output format is BGR. Here I change it to RGB manually
cv2_img = cv2.cvtColor(cv2_img, cv2.COLOR_BGR2RGB)
print((cv2_img == dmlc_img).all())    # False
```

Environment:
decord: 0.4.1
opencv-python: 4.2.0

**Comment by zhreshold** [comment]
Use https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_allclose.html, usually there's no guarantee that the two images are identical

**Comment by dai-ichiro** [comment]
You should convert dmlc_img from `decord.ndarray.NDArray` to `numpy.ndarray`.

Try this code.
```
cv2_img = cv2.cvtColor(cv2_img, cv2.COLOR_BGR2RGB)
print((cv2_img == dmlc_img.asnumpy()).all())
```
Hope this helps.

**Comment by Hao-Tju** [comment]
> Use https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_allclose.html, usually there's no guarantee that the two images are identical

I don't understand that. If two video frames decoded with OpenCV and decord are not identical, how can I guarantee the inference result of the corresponding frame with decord is correct?

**Comment by Hao-Tju** [comment]
> You should convert dmlc_img from `decord.ndarray.NDArray` to `numpy.ndarray`.
> 
> Try this code.
> 
> ```
> cv2_img = cv2.cvtColor(cv2_img, cv2.COLOR_BGR2RGB)
> print((cv2_img == dmlc_img.asnumpy()).all())
> ```
> 
> Hope this helps.

Thanks for your suggestions. This is a typo in the original source code. Converting dmlc_img from NDArray to numpy.ndarray is not helpful for the final results. I doubt that whether this is caused by the difference in decoders. The video decoder adopted by the OpenCV is FFMPEG in my experiment environment.

**Comment by trifle** [comment]
Hi @Hao-Tju ,

My interpretation would be that decoding does not need to be deterministic, depending on the compression standard and decoder implementation. Even if it is, there may be additional postprocessing steps, or differences in output formats including colorspace translations and rounding errors.

If you want to have a very robust test, approximate perceptive similarity tests would be a way to go.

**Comment by Hao-Tju** [comment]
> Hi @Hao-Tju ,
> 
> My interpretation would be that decoding does not need to be deterministic, depending on the compression standard and decoder implementation. Even if it is, there may be additional postprocessing steps, or differences in output formats including colorspace translations and rounding errors.
> 
> If you want to have a very robust test, approximate perceptive similarity tests would be a way to go.

Thanks for your reply. It's very helpful to me.
Since the installation of the decord library requires the FFMPEG library, I think that the decord also use the FFMPEG to decode the corresponding video. And I cannot find any APIs in the document to print the decoding backend. Maybe the default codecs adopted in the decord is not FFMPEG.

**Comment by trifle** [comment]
@Hao-Tju Glad that was helpful.
Just in closing, another thing to keep in mind is that hardware-based en- and decoders (NVDEC, NVENC) might differ, and often are not very well documented. So if you're ever using the CUDA option in decord to decode videos on the GPU, that would be another potential source of divergences.

**Comment by Hao-Tju** [comment]
> @Hao-Tju Glad that was helpful.
> Just in closing, another thing to keep in mind is that hardware-based en- and decoders (NVDEC, NVENC) might differ, and often are not very well documented. So if you're ever using the CUDA option in decord to decode videos on the GPU, that would be another potential source of divergences.

Thanks a lot. Currently I will use CPU to do video decoding, and GPU is used to do model inference with MXNet. We will pay attention to that in the future.
