### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by xvjiarui** [dmlc/decord#109]
Hi @zhreshold 

#103 fixed an important issue when decoding some old dataset like UCF101. 

May I know when is the next release could include this fix?

**Comment by zhreshold** [comment]
@xvjiarui 0.4.2 is up for linux,  for mac there's some issues with the wheel builder so you may need to build it instead

**Comment by xvjiarui** [comment]
Thx very much! Linux is good enough for me.
