### ISSUE TITLE
Any way to install decord on Jetson nano

### ISSUE THREAD

**Issue by siriusmehta** [dmlc/decord#110]
Hi,

I tried installing decord on Jetson Nano:

**pip install decord --user

Error:**

ERROR: Could not find a version that satisfies the requirement decord (from versions: none)
ERROR: No matching distribution found for decord

Any help ?

**Comment by zhreshold** [comment]
jetson has an arm cpu and there's no prebuilt one, you can built from source follow the linux installation guide.

**Comment by siriusmehta** [comment]
Thanks @zhreshold .

I tried building decord from source following Linux instructions on Nano while the process I did bumped into an error related to libnvcuvid.so where I copied the libnvcuvid.so to CUDA_TOOLKIT_ROOT_DIR\lib64 and build went smooth. 

Post building and installing the python api :

cd ../python
python3 setup.py install --user

the installation happens sucessfully. 

but while import get the below error:

Type "help", "copyright", "credits" or "license" for more information.
>>> import decord 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sirius/.local/lib/python3.6/site-packages/decord-0.4.2-py3.6.egg/decord/__init__.py", line 4, in <module>
    from ._ffi.runtime_ctypes import TypeCode
  File "/home/sirius/.local/lib/python3.6/site-packages/decord-0.4.2-py3.6.egg/decord/_ffi/runtime_ctypes.py", line 8, in <module>
    from .base import _LIB, check_call
  File "/home/sirius/.local/lib/python3.6/site-packages/decord-0.4.2-py3.6.egg/decord/_ffi/base.py", line 43, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "/home/sirius/.local/lib/python3.6/site-packages/decord-0.4.2-py3.6.egg/decord/_ffi/base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/home/sirius/archiconda3/envs/mx1.7/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libnvidia-ml.so.1: cannot open shared object file: No such file or directory

Thanks

**Comment by siriusmehta** [comment]
This happens when I build it from source either directly  cloning the decord git repo then building or building it with the TVM app. In both the cases when I switch on the CUDA flag to ON in decord cmake. 

The build happens smooth but post the installation of decord python package tvm/python : python setup.py install Once I try to import it the above error comes. 

Also when I try to only run from the tvm app the same error comes.

On Jetson I have Cuda 10.2. Jetpack 4.4  (latest)

My guess is if it is building it with right version of CUDA. Or Am I missing something ?

Thanks

**Comment by zhreshold** [comment]
@siriusmehta I feel like this is related: https://forums.developer.nvidia.com/t/libnvidia-ml-so-1-cannot-open-shared-object-file-no-such-file-or-directory-with-cross-compiled-elf/48555/2

If I read that correctly, on jetson nano, GPU decoding may not work, you can turn off `USE_CUDA=OFF` to use CPU for decoding the videos.

**Comment by siriusmehta** [comment]
Thank you @zhreshold ,

I tried building **USE_CUDA=OFF** and the build was successfully.
