### ISSUE TITLE
Has anyone successfully installed the GPU version? I need your help, paid

### ISSUE THREAD

**Issue by xiaoyang-coder** [dmlc/decord#112]
Has anyone successfully installed the GPU version? I need your help, paid

**Comment by xiaoyang-coder** [comment]
/usr/bin/ld: /usr/local/lib/libavcodec.a(vc1dsp_mmx.o): relocation R_X86_64_PC32 against symbol `ff_pw_9' can not be used when making a shared object; recompile with -fPIC /usr/bin/ld: final link failed: Bad value collect2: error: ld returned 1 exit status CMakeFiles/decord.dir/build.make:1067: recipe for target 'libdecord.so' failed make[2]: *** [libdecord.so] Error 1 CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/decord.dir/all' failed make[1]: *** [CMakeFiles/decord.dir/all] Error 2 Makefile:129: recipe for target 'all' failed make: *** [all] Error 2 root@kml-task-6194-record-85215-pro

**Comment by xiaoyang-coder** [comment]
<img width="1050" alt="WX20201208-115718@2x" src="https://user-images.githubusercontent.com/43001198/101438126-9b41a380-394c-11eb-9063-0efaf9bf62ae.png">

**Comment by zhreshold** [comment]
@xiaoyang-coder Do you happen to get similar issue when CUDA build is turned off?
- If so, check ffmpeg dependency
- If not, it might relate to CUDA drive

The error `relocation R_X86_64_PC32 against symbol `ff_pw_9' can not be used when making a shared object` is indicating that your ffmpeg might be built statically.
If you want to stick with static ffmpeg library, try the suggested `-fPIC` for ffmpeg.
