### ISSUE TITLE
DECORDError when I use decord

### ISSUE THREAD

**Issue by liuheng92** [dmlc/decord#116]
raise #DECORDError(py_str(_LIB.DECORDGetLastError()))
decord._ffi.base.DECORDError: [09:27:10] /io/decord/src/video/video_reader.cc:125: Check failed: st_nb >= 0 (-1381258232 vs. 0) ERROR cannot find video stream with wanted index: -1

**Comment by zhreshold** [comment]
The error indicates that the video doesn't provide a valid video stream, at least from the view of ffmpeg

**Comment by ahkarami** [comment]
@zhreshold,
How we can handle above-mentioned issue?
I also faced the above issue.
Best

**Comment by ahkarami** [comment]
@yinweisu & @frankier & @mli @JoannaLXY

**Comment by liuheng92** [comment]
> @zhreshold,
> How we can handle above-mentioned issue?
> I also faced the above issue.
> Best

check your input video
