### ISSUE TITLE
build error with CUDA on

### ISSUE THREAD

**Issue by wizyoung** [dmlc/decord#122]
When built with cuda, an error pops up:

```shell
xxx/decord/src/video/nvcodec/cuda_mapped_frame.cc: In constructor ‘decord::cuda::CUMappedFrame::CUMappedFrame(decord::cuda::CUMappedFrame&&)’:
xxx/decord/src/video/nvcodec/cuda_mapped_frame.cc:43:68: error: cannot convert ‘CUVIDPROCPARAMS {aka _CUVIDPROCPARAMS}’ to ‘int’ in initialization
       ptr_{other.ptr_}, pitch_{other.pitch_}, params_{other.params_} {
                                                                    ^
make[2]: *** [CMakeFiles/decord.dir/src/video/nvcodec/cuda_mapped_frame.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/decord.dir/all] Error 2
make: *** [all] Error 2
```
platform: centos 7.6, gcc-c++ 4.8.5

when I change compiler to clang(3.4.2), the error changes to:
```shell
xxx/decord/src/video/nvcodec/cuda_mapped_frame.cc:43:55: error: no viable conversion from 'CUVIDPROCPARAMS'
      (aka '_CUVIDPROCPARAMS') to 'int'
      ptr_{other.ptr_}, pitch_{other.pitch_}, params_{other.params_} {
```

**Comment by zhreshold** [comment]
weird, aggregate initialization with no default constructor is c++11 feature(https://en.cppreference.com/w/cpp/language/aggregate_initialization) which should be supported by gcc 4.8+ or clang 3.4.2, possibly it's not implemented

**Comment by binhnd102** [comment]
I have the exact same problem as @wizyoung. My system: centos 7, gcc 4.8.5

**Comment by wizyoung** [comment]
> weird, aggregate initialization with no default constructor is c++11 feature(https://en.cppreference.com/w/cpp/language/aggregate_initialization) which should be supported by gcc 4.8+ or clang 3.4.2, possibly it's not implemented

Sorry for the late reply. Yes, it seems it's not implemented in gcc4.8.5 in centos 7. So I changed it to direct initialization and solved the problem.

**Comment by binhnd102** [comment]
@wizyoung sorry but can I have your solution? I'm struggling with this for days.

**Comment by wizyoung** [comment]
@binhnd102 Yes, change these six lines

https://github.com/dmlc/decord/blob/cd6f7b3b7fdac8174ca956354ffaf897f6b656b3/src/video/nvcodec/cuda_mapped_frame.cc#L41-L46

to the following:

```cpp
CUMappedFrame::CUMappedFrame(CUMappedFrame&& other){
    disp_info = other.disp_info;
    valid_ = other.valid_;
    decoder_ = other.decoder_;
    ptr_ = other.ptr_;
    pitch_ = other.pitch_;
    params_ = other.params_;
    other.disp_info = nullptr;
    other.valid_ = false;
}
```

**Comment by yunkchen** [comment]
> @binhnd102 Yes, change these six lines
> 
> https://github.com/dmlc/decord/blob/cd6f7b3b7fdac8174ca956354ffaf897f6b656b3/src/video/nvcodec/cuda_mapped_frame.cc#L41-L46
> 
> to the following:
> 
> ```c++
> CUMappedFrame::CUMappedFrame(CUMappedFrame&& other){
>     disp_info = other.disp_info;
>     valid_ = other.valid_;
>     decoder_ = other.decoder_;
>     ptr_ = other.ptr_;
>     pitch_ = other.pitch_;
>     params_ = other.params_;
>     other.disp_info = nullptr;
>     other.valid_ = false;
> }
> ```

`/home/chenyunkuo.cyk/decord/src/video/nvcodec/cuda_threaded_decoder.cc:12:18: fatal error: nvml.h: No such file or directory
 #include <nvml.h>`
It comes to new error.
