### ISSUE TITLE
"pip install decord" is not working on windows

### ISSUE THREAD

**Issue by martinbaerwolff** [dmlc/decord#125]
I get the following error messages:
ERROR: Could not find a version that satisfies the requirement decord
ERROR: No matching distribution found for decord

I also tried "pip install decord --upgrade" and "pip install decord==0.4.2" and "pip install decord==0.3.8"

Thanks in advance for any advice :)

**Comment by qdlmcfresh** [comment]
Had the same issue, downloaded the newest python verison from python.org and it worked

**Comment by martinbaerwolff** [comment]
For me, too. Thanks!
