### ISSUE TITLE
asnumpy() greatly increases time overhead

### ISSUE THREAD

**Issue by imyhxy** [dmlc/decord#127]
I am trying to load video frame for inference, but I found out that the `asnumpy()` function greatly increases the time overhead, without `asnumpy()`, the overall speed can reach **503.42 it/s**, and the speed drop to **416.92 it/s** after adding the `asnumpy()`, this is a reduction of approximately 17%. how can I reduce this overhead.

**Comment by zhreshold** [comment]
If you are going to use the frame in deep learning frameworks, check out the zero-copy deep learning bridges API: https://github.com/dmlc/decord#bridges-for-deep-learning-frameworks

Otherwise `asnumpy` is required, unfortunately, this does not support zero-copy feature
