### ISSUE TITLE
Question about seek

### ISSUE THREAD

**Issue by ahkarami** [dmlc/decord#130]
@zhreshold,
Thank you for your great repo. I have some questions about `seek` in decord:
1- What is the exact difference between `seek` & `seek_accurate`?
2- Is there a method to find out on which video frame the pointer related to VideoReader is located on? (e.g., frame with index 100)
3- Does the input video format (_e.g.,_ '.mp4'), and its codec (_e.g.,_ h264) affect the result of reading the video? [with various methods (e.g., directly access frames via `frame = vr[i]` or cv2 style reading via `vr.next()` or `seek` or `seek_accurate`)]
4- Does randomly reading video (_i.e.,_ `frame = vr[i]`) exactly return the i-th frame of the video (with any format & codec)? How about `seek` method? i.e., 
```python
vr.seek(i)
img = vr.next()
```
5- For example we have a long video (e.g., 90 min video with ~ 3 GB). If we want to access some parts of it repeatedly (e.g., clip1 = frame 100 up to 500, clip2 = frame 800 up to 1000, clip3 = frame 1900 up to 2500, ...) what is the best method (fastest & accurate) for access the frames of video?

**Comment by zhreshold** [comment]
In short, `seek_accurate` guarantees that you seek can to the desired position, while `seek` tries to do so, but it will very likely only seek to nearest keyframe. To dig deeper, you could refer to how I-frame, P-frame, B-frame works in video decoding.
BTW, indexing always use `seek_accurate`.

For your use case, it's okay to simply use `accurate seek` for e.g.,  `vr[100:500]`, but if you want to access the parts repeatedly, you can have multiple video reader, say, `vr1 = VideoReader('xx.mp4'), vr2 = VideoReader('xx.mp4')` to avoid seeking through a very long video repeatedly

**Comment by ahkarami** [comment]
@zhreshold,
Thank you very much for the complete explanation. Your description helped me a lot.
Best
