### ISSUE TITLE
Does decord support reading buffer?

### ISSUE THREAD

**Issue by yoosan** [dmlc/decord#137]
Hi, Does decord support reading buffer, instead of a path?
such as in pillow, we can read image by 
```
buff = BytesIO(filebytes)
image = Image.open(buff)
```
in pyav, read video by
```
buffer = BytesIO(read_content)
video_container = av.open(buffer)
```

**Comment by zhreshold** [comment]
Yes, it supports file-like objects, please refer to this example: https://github.com/dmlc/decord/blob/master/tests/python/unittests/test_video_reader.py#L97
