### ISSUE TITLE
PyPI 0.5.2 doesn't include AudioReader

### ISSUE THREAD

**Issue by highamdh** [dmlc/decord#151]
After installing version 0.5.2 from PyPI I am trying to use the AudioReader, however I get a `AttributeError: module 'decord' has no attribute 'AudioReader'`. I have checked the `site-packages` files and it seems that `audio_reader.py` is not in the package. Is this the expected behaviour? Do I have to install from source to use the AudioReader?

**Comment by huang-ziyuan** [comment]
Experiencing the same issue here. 
When will the latest version be updated to PyPI?

**Comment by zhreshold** [comment]
Included in 0.6.0
