### ISSUE TITLE
Does decord support VideoWriter?

### ISSUE THREAD

**Issue by nemonameless** [dmlc/decord#158]
Like cv2.VideoWriter, I want to read a video and draw something on each frame then save as a new video, but no need of saving frames. Does decord support VideoWriter like this?
```
    capture = cv2.VideoCapture(video_file)
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    writer = cv2.VideoWriter(out_path, fourcc, fps, (width, height))
    index = 1
    while (1):
        ret, frame = capture.read()
        if not ret:
            break
        im = np.array(frame)
        writer.write(im)
    writer.release()
```

**Comment by zhreshold** [comment]
decord is designed to process videos for faster reading, there's no plan for adding video writer at this moment, I will reopen if the plan changes.

**Comment by innat** [comment]
@zhreshold any update?
