### ISSUE TITLE
Cannot compile on windows 10

### ISSUE THREAD

**Issue by nicholasguimaraes** [dmlc/decord#20]
Hello, I have been trying to compile decord on windows 10 for the last couple of days. 

I don't know much about cmake so I am struggling a bit.

The problem I'm having is that when it cannot find FFMPEG. 

I changed the path to the libraries on FindFFmpeg.cmake , FFmpeg.cmake but it does not work.

I'm also passing in the command line the dir path to ffmpeg.  -DFFMPEG_DIR:PATH="ffmpeg"

Is there any example on windows that someone could share with me?

**Comment by zhreshold** [comment]
With the latest commit it should respect -DFFMPEG_DIR flag unless you didn't install the shared library of FFMPEG collectly. 
If you don't know how to install these libraries, please use `chocolatey` to manage the dependencies, or install using `pip install decord` directly.
