### ISSUE TITLE
Is pip installation a conflict?

### ISSUE THREAD

**Issue by wakanawakana** [dmlc/decord#200]
I have previously installed decode 0.6.0　.
Currently, decode exists in different projects.
https://github.com/deshima-dev/decode
Is there a conflict between "deshima-dev/decode" and pip installation?
![image](https://user-images.githubusercontent.com/24972079/151754312-937e4bda-7f6c-4890-bfc1-7ca38b336962.png)
![image](https://user-images.githubusercontent.com/24972079/151754455-9fa6e15a-c726-4ad1-9e47-806a96c9bd41.png)

**Comment by zhreshold** [comment]
It's decord not decode
