### ISSUE TITLE
question about random shuffle in VideoLoader

### ISSUE THREAD

**Issue by AceCoooool** [dmlc/decord#23]
Is it a choice for random frame in batch size ?
The shuffle=2 only shuffle between batch size. (For example, batch=4, the index of one batch is contiguous---like `22, 23, 24, 25`). But I want to get something like `22, 28, 12, 40` (random).

Thank you!

**Comment by zhreshold** [comment]
Hi, complicated shuffling is not implemented yet. You can implement flexible random behavior by using VideoReader.get_batch() now.

**Comment by AceCoooool** [comment]
Thank you. The `get_batch` is nearly the same time as the `VideoReader` in random index one by one even the batch_size=16. Is there a quicker way to get random frame from video ?

**Comment by zhreshold** [comment]
@AceCoooool Can you explain your use case? The time of random accessing one frame is not predictable due to allocation of key frames and current seeking position. `get_batch` can saves c++ to python api call overhead but won't reduce the internal video seeking and decoding overhead.

**Comment by AceCoooool** [comment]
thank you. I want to load video rather than convert video to images to train a classifier. So I want to random read one frame from video.

**Comment by zhreshold** [comment]
@AceCoooool Okay, you can use the VideoReader with shuffled list to access the random frames. Example here: https://github.com/dmlc/decord/blob/master/examples/video_reader.ipynb, only difference is that I use `arange` here but you can definitely try shuffle the list first.
