### ISSUE TITLE
Return timestamps

### ISSUE THREAD

**Issue by yjxiong** [dmlc/decord#26]
When reading video frames, it is nice to also return the actual timestamps of the read frames. This will be a great feature for applications like VOS and tracking.

**Comment by zhreshold** [comment]
@yjxiong Are you referring to `VideoReader`? With indices already known for `VideoReader` I think it's just a matter of plain calculation given the FPS of the video is already known and constant. See `VideoReader.get_avg_fps()`

However, if the video has variable FPS, then it might involve additional records in the decoding backend. What do you think?

**Comment by yjxiong** [comment]
Yes! For constant FPS this is fine. For variable FPS videos or videos with lost/unreadable frames the FPS-based calculation could be problematic. There is a reference implementation using ffmpeg that gets the exact timestamp of each frame (some video players also use this). 

https://github.com/opencv/opencv/pull/14901/files
