### ISSUE TITLE
Makefile generates error: ‘AVBSFContext’ was not declared in this scope; did you mean ‘AVIOContext’?

### ISSUE THREAD

**Issue by MiraWelner** [dmlc/decord#276]
I am attempting to install decord on gpu. I have conda installed and it can read the gpu. However regardless of how i compile the makefile, I get the result:

In file included from /home/punky/Documents/decord/src/audio/../../include/decord/audio_interface.h:9,
                 from /home/punky/Documents/decord/src/audio/audio_reader.h:10,
                 from /home/punky/Documents/decord/src/audio/audio_interface.cc:5:
/home/punky/Documents/decord/src/audio/../../include/decord/../../src/video/ffmpeg/ffmpeg_common.h:187:5: error: ‘AVBSFContext’ was not declared in this scope; did you mean ‘AVIOContext’?
  187 |     AVBSFContext, Deleterp<AVBSFContext, void, av_bsf_free> >;
      |     ^~~~~~~~~~~~
      |     AVIOContext
/home/punky/Documents/decord/src/audio/../../include/decord/../../src/video/ffmpeg/ffmpeg_common.h:187:28: error: ‘AVBSFContext’ was not declared in this scope; did you mean ‘AVIOContext’?
  187 |     AVBSFContext, Deleterp<AVBSFContext, void, av_bsf_free> >;
      |                            ^~~~~~~~~~~~
      |                            AVIOContext
/home/punky/Documents/decord/src/audio/../../include/decord/../../src/video/ffmpeg/ffmpeg_common.h:187:48: error: ‘av_bsf_free’ was not declared in this scope; did you mean ‘av_opt_free’?
  187 |     AVBSFContext, Deleterp<AVBSFContext, void, av_bsf_free> >;
      |                                                ^~~~~~~~~~~
      |                                                av_opt_free
/home/punky/Documents/decord/src/audio/../../include/decord/../../src/video/ffmpeg/ffmpeg_common.h:187:59: error: template argument 1 is invalid
  187 |     AVBSFContext, Deleterp<AVBSFContext, void, av_bsf_free> >;
      |                                                           ^
/home/punky/Documents/decord/src/audio/../../include/decord/../../src/video/ffmpeg/ffmpeg_common.h:187:59: error: template argument 3 is invalid
/home/punky/Documents/decord/src/audio/../../include/decord/../../src/video/ffmpeg/ffmpeg_common.h:187:61: error: template argument 1 is invalid
  187 |     AVBSFContext, Deleterp<AVBSFContext, void, av_bsf_free> >;
      |                                                             ^
/home/punky/Documents/decord/src/audio/../../include/decord/../../src/video/ffmpeg/ffmpeg_common.h:187:61: error: template argument 2 is invalid
make[2]: *** [CMakeFiles/decord.dir/build.make:76: CMakeFiles/decord.dir/src/audio/audio_interface.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/decord.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

I do not know what this means? any advice appreciated

**Comment by egorovivannn** [comment]
You have to put some cuda files inside container during installation. 
You can see how it can be done here:
https://github.com/egorovivannn/decord_image

**Comment by MiraWelner** [comment]
thank you! this fixed it
