### ISSUE TITLE
could decord support aarch64？

### ISSUE THREAD

**Issue by Tyx-main** [dmlc/decord#288]
I  want to use aarch64 machine to install decord, but it seems that decord has not supported platform of aarch64, is there any method to use decord on aarch64？

**Comment by Tyx-main** [comment]
@zhreshold

**Comment by petered** [comment]
See fork: https://github.com/georgia-tech-db/eva-decord .  That supports it.

**Comment by Tyx-main** [comment]
> See fork: https://github.com/georgia-tech-db/eva-decord . That supports it.

Thanks for your reply.
