### ISSUE TITLE
Jetson Decoder?

### ISSUE THREAD

**Issue by johnnynunez** [dmlc/decord#320]

**Comment by NeighborhoodCoding** [comment]
Decord can leverage NVIDIA’s NVDEC hardware acceleration on systems with supported NVIDIA GPUs, including Jetson platforms. However, Jetson boards typically require building Decord from source and ensuring that all dependencies (FFmpeg with NVDEC support, CUDA toolkit, and the necessary headers) are installed properly on the device.

**Comment by johnnynunez** [comment]
> Decord can leverage NVIDIA’s NVDEC hardware acceleration on systems with supported NVIDIA GPUs, including Jetson platforms. However, Jetson boards typically require building Decord from source and ensuring that all dependencies (FFmpeg with NVDEC support, CUDA toolkit, and the necessary headers) are installed properly on the device.

jetson not use nvenc, use his "jetson multimedia"
