### ISSUE TITLE
How to prevent annoying ffmpeg log

### ISSUE THREAD

**Issue by kennymckormick** [dmlc/decord#34]
I use ffmpeg 4.0 and install decord(0.3.5) on my linux machine with pip install. When I load videos with decord, the annoying log '[swscaler @ 0x7fc932c27040] deprecated pixel format used, make sure you did set range correctly' keeps appearing. Is it possible to prevent such logs from appearing(videos are loaded properly)?

**Comment by zhreshold** [comment]
A temporary workaround is to redirect stderr to /dev/null, these are low level warnings generated by ffmpeg so decord cannot catch the warnings.

Also the warnings indicate that the video is typically using old encoder that's deprecated long time  ago, so re-encode the video can eliminate the warnings as well

**Comment by kennymckormick** [comment]
Thank you! That's a good solution.

**Comment by huww98** [comment]
I think I've found a better solution. [PyAV](https://github.com/mikeboers/PyAV) will hook into the FFmpeg log system and route messages to Python `logging` module. So, I link decord and PyAV to the same FFmpeg shared object. After just `import av`, these low priority logs will not be shown.

Here I share the Dockerfile I used to build & install decord and PyAV:
```Dockerfile
FROM pytorch/pytorch:1.4-cuda10.1-cudnn7-devel as builder

RUN echo "deb https://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu bionic main" > /etc/apt/sources.list.d/jonathonf-ubuntu-ffmpeg-4-bionic.list && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4AB0F789CBA31744CC7DA76A8CF63AD3F06FC659 && \
    apt-get update && \
    apt-get install -y build-essential make cmake \
                       libavcodec-dev libavfilter-dev libavformat-dev libavutil-dev

FROM builder as decord-builder
RUN git clone --depth=5 --recursive https://github.com/dmlc/decord.git /decord && \
    cd /decord && \
    git checkout ad6ab998e0a7dc161f01a72c8095a0c2711630a4
RUN cd /decord && \
    mkdir build && cd build && \
    cmake .. && \
    make -j 16 && \
    cd ../python && \
    python setup.py bdist_wheel

FROM builder as pyav-builder
RUN apt-get update && \
    apt-get install -y pkg-config libavdevice-dev
RUN pip wheel --no-binary=av av

FROM pytorch/pytorch:1.4-cuda10.1-cudnn7-runtime as runtime
RUN apt-get update && \
    apt-get install -y --no-install-recommends gnupg2 && \
    echo "deb https://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu bionic main" > /etc/apt/sources.list.d/jonathonf-ubuntu-ffmpeg-4-bionic.list && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4AB0F789CBA31744CC7DA76A8CF63AD3F06FC659 && \
    apt-get update && \
    apt-get install -y libavcodec58 libavfilter7 libavformat58 libavutil56 && \
    rm -rf /var/lib/apt/lists/*
COPY --from=decord-builder /decord/python/dist/decord-*.whl /wheels/
COPY --from=pyav-builder /workspace/av-*.whl /wheels/
RUN python -m pip install /wheels/*.whl
```

Using the `logging` module, we can control how to deal with these logs now. Hopes this is helpful
