### ISSUE TITLE
Document how to build a manylinux1 wheel

### ISSUE THREAD

**Issue by alesanfra** [dmlc/decord#36]
Hi,

For a project I need to use a more updated version of `decord` than the one present on pypi.org.
Ideally I would like to build a `manylinux1_x86_64` wheel and to publish it on our internal pypi repository, but I'm having hard time to compile decord on the official docker image (quay.io/pypa/manylinux1_x86_64).

Can you please share the procedure you use to build wheels?

Thanks in advance!

**Comment by zhreshold** [comment]
YOu can take a look at this repo: https://github.com/zhreshold/decord-distro

**Comment by alesanfra** [comment]
That's exactly what I need, thanks a lot!
