### ISSUE TITLE
GPU decode error

### ISSUE THREAD

**Issue by wizyoung** [dmlc/decord#41]
I find that in the gpu mode, some videos cannot be decoded correctly while in the cpu mode everything works fine.

Take [v_ApplyEyeMakeup_g11_c02.avi.zip](https://github.com/dmlc/decord/files/4399551/v_ApplyEyeMakeup_g11_c02.avi.zip) from ucf101 dataset for example:

```python
import decord as de
vr = de.VideoReader('./v_ApplyEyeMakeup_g11_c02.avi', ctx=de.gpu(0))
```

The error pops out like:
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wizyoung/.local/lib/python3.7/site-packages/decord-0.3.6-py3.7.egg/decord/video_reader.py", line 37, in __init__
    uri, ctx.device_type, ctx.device_id, width, height)
  File "/home/wizyoung/.local/lib/python3.7/site-packages/decord-0.3.6-py3.7.egg/decord/_ffi/_ctypes/function.py", line 175, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/wizyoung/.local/lib/python3.7/site-packages/decord-0.3.6-py3.7.egg/decord/_ffi/base.py", line 63, in check_call
    raise DECORDError(py_str(_LIB.DECORDGetLastError()))
decord._ffi.base.DECORDError: [02:40:48] /home/wizyoung/my_env/decord/src/video/nvcodec/cuda_threaded_decoder.cc:83: Check failed: bsf Error finding bitstream filter: 
```

Env:
ffmpeg 4.1.5, cuda 10.1.243, NV Tesla V100 on Ubuntu 18.04

BTW: I find decord in cpu mode sometimes runs slower than opencv videocapture on many videos. (tested on ucf101 dataset)

**Comment by zhreshold** [comment]
@wizyoung  Can you post the information on the file `v_ApplyEyeMakeup_g11_c02.avi` here?

The comparison with opencv is not apple to apple, opencv doesn't support accurate frame seeking.

**Comment by zhreshold** [comment]
@wizyoung Can you also attach the video file here?

**Comment by wizyoung** [comment]
@zhreshold Hi, I have already attached the video in the issue description. Please click the url (https://github.com/dmlc/decord/files/4399551/v_ApplyEyeMakeup_g11_c02.avi.zip) to download it.

**Comment by zhreshold** [comment]
Fixed in https://github.com/dmlc/decord/commit/83d4c63eb5e3870ecea3c6b1a115061a3b625090

Closing for now, let me know if you have more questions regarding this.
