### ISSUE TITLE
 CUDA not enabled. Requested context GPU(0).

### ISSUE THREAD

**Issue by lucheng07082221** [dmlc/decord#71]

**Comment by ecr23xx** [comment]
Same question here. Any update or solution?

**Comment by zhreshold** [comment]
if you are using `pip install decord`, it's compiled without cuda. Checkout https://github.com/dmlc/decord#install-from-source for instruction to build with cuvid

**Comment by ecr23xx** [comment]
@zhreshold Thanks. My problem is compile from source by `cmake .. -DUSE_CUDA=0` instead of `cmake .. -DUSE_CUDA=ON`. Maybe it's typo in README?
