### ISSUE TITLE
[Feature Requests] Support read file from file-like object.

### ISSUE THREAD

**Issue by DelightRun** [dmlc/decord#73]
Let VideoReader support read from file-like object, i.e. `BytesIO`, will make a lot benefits:

+ It can be compatible with many third-party filesystem interfaces, such as GFile and [PyFilesystem](https://docs.pyfilesystem.org/en/latest/#)
+ It can be very convenient to access cloud-storage, such as [S3 on AWS](https://aws.amazon.com/s3/?nc1=h_ls) and [OSS on AlibabaCloud](https://cn.aliyun.com/product/oss)

Currently I have to download my videos from remote into temporary files before initializing `VideoReader` like this:

```python
tmpfile = tempfile.NamedTemporaryFile('wb', delete=False)
fp = bucket.get_object('xxx/xxx.mp4')
tmpfile.write(fp.read())
container = decord.VideoReader(tmpfile.name, ctx=decord.cpu(0)
# DO DECODE
```

But in PyAV, I can access and decode my video just like this:

```python
fp = bucket.get_object('xxx/xxx.mp4')
container = av.open(BytesIO(fp.read()))
# DO DECODE
```

**Comment by zhreshold** [comment]
Shall be closed by #75 

```python
fp = bucket.get_object('xxx/xxx.mp4')
container = decord.VideoReader(fp, ctx=decord.cpu(0))
```
