### ISSUE TITLE
Which cpu is used when using device=cpu(0)

### ISSUE THREAD

**Issue by YuqiHUO** [dmlc/decord#74]
Hi, thanks for the awesome Decord, when I wanna use GPU to read videos, I can specify the specific gpu(0)-gpu(7), but there are too many CPUs in the server, does that mean when I set de default cpu(0), only one CPU will be used for reading?

**Comment by zhreshold** [comment]
In fact there's currently no specific handling of cpu devices like gpu ids, so cpu device is now handled by system. I do not have a multi-cpu workstation to test but it's very likely that all cpus will be used

**Comment by YuqiHUO** [comment]
thanks!
