### ISSUE TITLE
[Feature Request] get_frame_timestamp in integral units (e.g. flicks)

### ISSUE THREAD

**Issue by Erotemic** [dmlc/decord#79]
I'm only getting my feet wet with video encoding schemes, so forgive (and please correct) me if I say anything uniformed. 

Seconds in floating point format, while intuitive, can lead to numerical issues. It would be nice there was an integral representation of time that was not subject to floating point errors. A unit that seems nice for this is the ["flick"](https://en.wikipedia.org/wiki/Flick_(time)). A flick is a unit of time equal to exactly 1/705,600,000, which was chosen to be divisible by the most common sampling frequencies. 

The [code seems](https://github.com/dmlc/decord/blob/449a9ffe8aaace5606007d9b98a2cdc15d89d9ac/src/video/video_reader.cc#L434) to use this concept of PTS to implement the get_frame_timestamp function. Looking up [PTS](https://en.wikipedia.org/wiki/Presentation_timestamp) I found out that it was a presentation time stamp, and it seems to be encoded as an integer in the backend, but I'm not sure what unit it is using.  ~~Line 444 seems to simply statically cast this int64 directly into a float32, but I don't see any unit conversion~~. *Totally missed that the int64 was the shape and the float32 was the value; I get confused dealing with strongly typed languages sometimes (which is odd considering they are even more explicit about what's happening)*.

What exactly is the PTS encoding here? And is it possible / useful to add some API that returns some integral representation of time?

**Comment by zhreshold** [comment]
The current pts is in fp32 which is not accurate but should be sufficient for seeking and estimation purposes. Do you have any specific use case that require accurate timestamp?

**Comment by Erotemic** [comment]
No, its just preempting a problem that I can foresee existing. Feel free to triage as necessary.
