### ISSUE TITLE
Slower than opencv

### ISSUE THREAD

**Issue by mhubii** [dmlc/decord#87]
Hi,

I have written a small benchmark, and decord is slower than opencv. Times on my machine are

 - cv benchmark time: 9.04
 - decord benchmark time: 12.77
 - decord batch benchmark time: 11.80

Why is that? See code below to rerun

```python
import cv2

from decord import VideoReader, VideoLoader
from decord import cpu

import time
import numpy as np

# open video stream, sample sequence, measure time

def sample_sequence_cv(file_name, offset, sequence_length):
    vc = cv2.VideoCapture(file_name)

    vc.set(1, offset)

    seq = []
    for _ in range(sequence_length):
        ret, img = vc.read()
        seq.append(img)
    
    return seq

def sample_sequence_decord(file_name, offset, sequence_length):
    vr = VideoReader(file_name, num_threads=sequence_length)

    seq = []
    for i in range(sequence_length):
        seq.append(vr[offset + i])
    
    return seq


def sample_batch_decord(file_name, offset, sequence_length):
    vr = VideoReader(file_name, num_threads=sequence_length)

    idcs = np.arange(offset, offset+sequence_length)
    seq = vr.get_batch(idcs)
    
    return seq


if __name__ == '__main__':

    file_name = 'video.mp4'
    sequence_length = 10

    start = time.time()
    for offset in range(10000,10100):
        seq = sample_sequence_cv(file_name, offset, sequence_length)
    print('cv benchmark time: {}'.format(time.time() - start))

    start = time.time()
    for offset in range(10000,10100):
        seq = sample_sequence_decord(file_name, offset, sequence_length)
    print('decord benchmark time: {}'.format(time.time() - start))

    start = time.time()
    for offset in range(10000,10100):
        seq = sample_batch_decord(file_name, offset, sequence_length)
    print('decord batch benchmark time: {}'.format(time.time() - start))

```

**Comment by mhubii** [comment]
Seems like decord has a bit of an over head

**Comment by zhreshold** [comment]
@mhubii few things

- did you build for release?
- opencv seek by `set` is not accurate, being able to seek to keyframes and a random frame is different story
- create `VideoReader` inside a loop is not a good practice, the creation itself has overhead. Comparing to cv2 videocapture which is a thin wrapper, VideoReader has to maintain more states to ensure seeking performance. Try to reuse the `VideoReader` as much as possible

**Comment by mhubii** [comment]
Hi @zhreshold, thanks for the reply, I appreciate it. 

I have just used the pip packaged libraries. Yes good point, I moved the constructor out of the for loop after posting this code snipped, and decord turns out to be slightly faster, but not as fast as in the benchmarks.

**Comment by DinoMan** [comment]
> I have just used the pip packaged libraries. Yes good point, I moved the constructor out of the for loop after posting this code snipped, and decord turns out to be slightly faster, but not as fast as in the benchmarks.

Can I ask how did does moving the constructor outside the for loop help. It seems that whenever you want to read a new file you have to instantiate a new VideoReader anyway. Am I missing something?
