### ISSUE TITLE
Installation of decord through pip is not working in Anaconda

### ISSUE THREAD

**Issue by Jerburi** [dmlc/decord#92]
Hi,

I was using decord without a problem in Anaconda, until I had a problem in my environment 2 weeks ago and I had to re-install everything. Now, after reinstalling decord through pip, it does not work. To be more precise, the package is effectively installed, with its folders and __init__.py file where they should be. However, when I try to import the module in python, it throws the following error:

```
Python 3.6.10 (default, Mar  5 2020, 10:17:47) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import decord
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\ephys\lib\site-packages\decord\__init__.py", line 4, in <module>
    from ._ffi.runtime_ctypes import TypeCode
  File "C:\Anaconda3\envs\ephys\lib\site-packages\decord\_ffi\runtime_ctypes.py", line 8, in <module>
    from .base import _LIB, check_call
  File "C:\Anaconda3\envs\ephys\lib\site-packages\decord\_ffi\base.py", line 43, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "C:\Anaconda3\envs\ephys\lib\site-packages\decord\_ffi\base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "C:\Anaconda3\envs\ephys\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

Seems a dependency is not found, but I don't have the knowledge to understand which one. Could you help me sort this problem out?

**Comment by zhreshold** [comment]
My guess it that your machine don't have vc++ runtime installed, you can try installing the runtime first: https://support.microsoft.com/en-ca/help/2977003/the-latest-supported-visual-c-downloads

Precisely, winError 126 is a dll missing error, however, there's not much you can do to decipher it in python. The correct path to find the missing dependency is through https://github.com/lucasg/Dependencies, you can drag n drop the libdecord.dll to the dependency checker to find the missing dll.

**Comment by Jerburi** [comment]
Hi zhreshold,

I uninstalled decord, then installed the latest version of VC++ (2015-2017-2019), and reinstalled decord again. It didn't work for me, it still shows the same problem.

I checked the dependency walker (nice tool by the way!), but sorting out the dependencies is not a task I can deparate time at the moment...

Thanks for your help,

Jorge

**Comment by Jerburi** [comment]
Hi again!

I found the solution by chance. Turns out windows had a recent update, and some Media Service packages were removed on it. I noticed it because my opencv v4.4 wasn't woking either.

As soon as I installed this packages (as explained in [this stackoverflow entry](https://stackoverflow.com/a/55361292/14221390)) and restarted the computer, everything worked.

**Comment by zhreshold** [comment]
@Jerburi Awesome, thanks for coming back to the issue and provide the solution!

**Comment by Jerburi** [comment]
I'm happy if it could help others whjile sorting these windows-related difficulties....

By the way, I just found that the most permanent solution to this problem is to set the Windows 10 N to install the Media Features as an add-on, as explained [in this link](https://support.microsoft.com/en-us/help/4562569/media-feature-pack-for-windows-10-n-may-2020)
