### ISSUE TITLE
when i set width=48, height=27, VideoReader get(n,27,48,4L),not(n,27,48,3L).

### ISSUE THREAD

**Issue by dlliyang** [dmlc/decord#93]
when i set  vr = decord.VideoReader(file_path, ctx=decord.cpu(0), width=48, height=27, num_threads=10),i get (n,27,48,4L),i want't to know why?thanks.

**Comment by zhreshold** [comment]
Seems like your video has 4 channels, presumably RGBA.

**Comment by WUMINGCHAzero** [comment]
hello~ may i ask what's the format of your input video? @dlliyang  I want to read rgba video.
Thanks!
