### ISSUE TITLE
How to set fps for extracting frames?

### ISSUE THREAD

**Issue by i-am-flashh** [dmlc/decord#95]
I am using decord to extract frames and it does a good job, by default it uses the video fps( i guess). 
lets say i need to extract frame at specific fps like 0.2 or any other value.

example : i have a video at 48 seconds and its fps is 30.
when i extract i get 1440 frames

But, I need to specify the fps like **0.2**
so , the output should be 10 frames.

PS. In ffmpeg, we can specify the fps while extracting. I am asking in the same way.

My code:

vr = VideoReader("nature.mp4")
vr._avg_fps = 0.2  ##Not worked
for i in range(len(vr)):
                frame = vr[i].asnumpy()
                plt.imsave(f'{name}_Frame_{i}.jpg',frame)

Help appreciated

**Comment by radiantly** [comment]
You could do a quick calculation and skip a number of frames. Example:

```python
vr = VideoReader("nature.mp4")
fps = vr.get_avg_fps()
required_fps = 0.2
frames_to_skip = int(fps / required_fps)
for i in range(0, len(vr), frames_to_skip):
     frame = vr[i].asnumpy()
     plt.imsave(f'{name}Frame{i}.jpg',frame)
```

**Comment by zhreshold** [comment]
Your example is based on FFMPEG's re-encoding, there's no decoding based method that can shrink the 1440 frames to 10 frames without any advanced interpolation.

Decord is a pure decoder so the FPS of VideoReader is a property, you can't set the new FPS to the object and let the magic happen. As a workaround, use subsampling as @radiantly mentioned.

**Comment by yeliudev** [comment]
> Your example is based on FFMPEG's re-encoding, there's no decoding based method that can shrink the 1440 frames to 10 frames without any advanced interpolation.
> 
> Decord is a pure decoder so the FPS of VideoReader is a property, you can't set the new FPS to the object and let the magic happen. As a workaround, use subsampling as @radiantly mentioned.

Hi @zhreshold, thanks for sharing! I would like to confirm that if we are using the subsampling method as @radiantly mentioned, is there a chance that the extracted frames may not be uniform in the temporal domain, as there would not be any interpolations among raw frames?
