### ISSUE TITLE
Update release in PyPi

### ISSUE THREAD

**Issue by xvjiarui** [dmlc/decord#96]
Hi @zhreshold 
First of all, thanks for this awsome tool. 
The version in PyPi is still 0.4.0, released on June 24, 2020. And there is some important fix like #82 in July. 
So the PyPi version a little bit out of date. Could you please release the new version on PyPi?

**Comment by zhreshold** [comment]
Linux build should be up already, there are a couple issues with the builder for Mac OS and windows, I will try several fixes later.
